### ISSUE TITLE
Broken links in Python SDK documentation with docusaurus v3

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-sdk-python#270]
**Describe the bug**
All reference links in the Python SDK documentation are broken after migrating docusausus to v3. For example, on the [storages concept page](https://docs.apify.com/sdk/python/docs/concepts/storages), none of the links to reference materials are functioning correctly.

**To Reproduce**
1. Bump docusaurus to v3
2. Go to '[storages concept page](https://docs.apify.com/sdk/python/docs/concepts/storages)'
3. Click on any link in the reference section.
4. Observe that the links lead to non-existent pages, resulting in a 404 error.

**Expected behavior**
All links in the Python SDK documentation should correctly lead to the intended reference pages without resulting in errors.

**Where was this bug reported**
https://apify.slack.com/archives/C0L33UM7Z/p1725871628149089

**Comment by barjin** [comment]
A closer investigation shows that this is not caused by the Docusaurus v3 update but by changes to the actual code base.

See e.g. https://github.com/apify/apify-sdk-python/commit/2f9dcc559414f31e3f4fc87e72417a36494b9c84 - this turns `Actor` from a class to a global variable and moves the class definition into `_ActorType` (which is a "private" name, by `pydoc-markdown`'s standards). 

I'm not too sure how to handle this. In a perfect world, the project architecture would play nicely with how we document things (and how it's understandable for users), but I get that this is not always possible. 

Maybe a question for @janbuchar - with the static `Actor` instance now, how would you expect to see this in the docs? Can we consider the `Actor` instance a "class" with all static methods for the sake of documentation? Or are there other caveats?

**Comment by janbuchar** [comment]
@barjin the reason for the change was to avoid bending the Python object mechanics too much. This was hard to read and maintain. If you know a way to make the docs think that `Actor` is a "static class", I say go for it.

**Comment by barjin** [comment]
> If you know a way to make the docs think that Actor is a "static class", I say go for it.

Well, it certainly can be done, but it would be just another custom hack :/

Are there any other places with such changes that you can think of? [All the storage clients](https://docs.apify.com/sdk/python/reference/class/ApifyStorageClient) are missing their methods too 🤔
